version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: finance_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${DB_NAME:-finance_db}
      MYSQL_USER: ${DB_USER:-finance_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-finance_pass}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: finance_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      ai:
        condition: service_started
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER:-finance_user}
      DB_PASSWORD: ${DB_PASSWORD:-finance_pass}
      DB_NAME: ${DB_NAME:-finance_db}
      JWT_SECRET: ${JWT_SECRET:-devsecret}
      AI_SERVICE_URL: http://ai:8000
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./backend:/app

  ai:
    build: ./ai-service
    container_name: finance_ai
    restart: unless-stopped
    environment: {}
    ports:
      - "8000:8000"
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    working_dir: /app
    volumes:
      - ./ai-service:/app

  frontend:
    build: ./frontend
    container_name: finance_frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  db_data:

