services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fin_db
      MYSQL_USER: fin_user
      MYSQL_PASSWORD: fin_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ai-service
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm","run","dev"]

  ai-service:
    build: ./ai-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/app
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--reload"]

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm","run","dev","--","--host"]

volumes:
  db_data:
